FROM node:18@sha256:c8a65828bb3f921484bb25fec05b2909a9375a42b2932acd69b6a0fc1117aeb5 as build

ENV NODE_ENV=production
ENV NEXT_OUTPUT_STANDALONE=true

ADD https://github.com/cds-snc/static-content-lambda/raw/main/release/latest/lambda-static-server /lambda-static-server
RUN chmod 755 /lambda-static-server

COPY . /src
WORKDIR /src

RUN corepack enable && yarn set version berry
RUN yarn install
RUN yarn build

FROM scratch

COPY --from=build /src/build /var/www/html
COPY --from=build /lambda-static-server /lambda-static-server

ENTRYPOINT [ "/lambda-static-server" ]