FROM node:18@sha256:4297f0e1f6f0c65981991c8105d8f36a242b5e6f902274676ba41f0266530823 as build

ENV NODE_ENV=production
ENV NEXT_OUTPUT_STANDALONE=true

ADD https://github.com/cds-snc/static-content-lambda/raw/main/release/latest/lambda-static-server /lambda-static-server
RUN chmod 755 /lambda-static-server

COPY . /src
WORKDIR /src

RUN corepack enable && yarn set version berry
RUN yarn install
RUN yarn build

FROM scratch

COPY --from=build /src/build /var/www/html
COPY --from=build /lambda-static-server /lambda-static-server

ENTRYPOINT [ "/lambda-static-server" ]