name: Build and deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::283582579564:role/threat-modeling-tool-apply
          aws-region: ca-central-1

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 0
          ref: main

      - name: Build
        run: yarn install && yarn build

      - name: Deploy and invalidate cache
        run: |
          aws s3 sync ./build s3://threat-modeling.cdssandbox.xyz-f3pn8icp/ --delete
          aws cloudfront create-invalidation --cli-input-json "{\"DistributionId\":\"E3989RAVFXNM48\",\"InvalidationBatch\":{\"Paths\":{\"Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":\"$(date +%s)\"}}"
