name: "Terraform Apply"

on:
  push:
    branches:
      - main

jobs:
  terragrunt-apply:
    uses: cds-snc/workflows/.github/workflows/terragrunt-apply.yml@main
    with:
      module: terraform
      role_arn: arn:aws:iam::283582579564:role/threat-modeling-tool-apply
      terraform_version: 1.3.3
      terragrunt_version: 0.31.1
